CLASS zcl_170422045_sel_table_exc DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_170422045_sel_table_exc IMPLEMENTATION.
ENDCLASS.
